# Generated by Django 5.2.9 on 2026-04-23 19:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_terms', models.TextField(help_text='Uno por línea', verbose_name='Términos de búsqueda')),
                ('locations', models.TextField(help_text='Una por línea', verbose_name='Ubicaciones')),
                ('sites', models.TextField(default='indeed', help_text='Separados por coma: indeed, linkedin, glassdoor, google', verbose_name='Sitios')),
                ('country', models.CharField(default='mexico', max_length=50, verbose_name='País')),
                ('results_wanted', models.PositiveIntegerField(default=50, verbose_name='Resultados por búsqueda')),
                ('hours_old', models.PositiveIntegerField(default=72, verbose_name='Antigüedad máxima (horas)')),
                ('total_jobs_found', models.PositiveIntegerField(default=0, verbose_name='Total empleos encontrados')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ejecución')),
                ('duration_seconds', models.FloatField(default=0, verbose_name='Duración (segundos)')),
                ('status', models.CharField(choices=[('running', 'En ejecución'), ('completed', 'Completada'), ('failed', 'Fallida')], default='running', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
            ],
            options={
                'verbose_name': 'Búsqueda',
                'verbose_name_plural': 'Búsquedas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255, verbose_name='ID del empleo')),
                ('site', models.CharField(blank=True, default='', max_length=50, verbose_name='Sitio')),
                ('title', models.CharField(blank=True, default='', max_length=500, verbose_name='Título')),
                ('company', models.CharField(blank=True, default='', max_length=300, verbose_name='Empresa')),
                ('location', models.CharField(blank=True, default='', max_length=300, verbose_name='Ubicación')),
                ('job_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('date_posted', models.CharField(blank=True, default='', max_length=100, verbose_name='Fecha publicación')),
                ('min_amount', models.CharField(blank=True, default='', max_length=50, verbose_name='Salario mínimo')),
                ('max_amount', models.CharField(blank=True, default='', max_length=50, verbose_name='Salario máximo')),
                ('currency', models.CharField(blank=True, default='', max_length=10, verbose_name='Moneda')),
                ('interval', models.CharField(blank=True, default='', max_length=50, verbose_name='Intervalo salarial')),
                ('job_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo de empleo')),
                ('search_location', models.CharField(blank=True, default='', max_length=200, verbose_name='Ubicación de búsqueda')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.searchconfig', verbose_name='Búsqueda')),
            ],
            options={
                'verbose_name': 'Oferta de empleo',
                'verbose_name_plural': 'Ofertas de empleo',
                'ordering': ['-id'],
            },
        ),
    ]
