# Generated by Django 5.2.9 on 2026-04-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchconfig',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='Solo remoto'),
        ),
    ]
