# Generated by Cursor on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_searchconfig_is_remote"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobresult",
            constraint=models.UniqueConstraint(
                fields=("search", "site", "job_id"),
                name="uniq_job_per_search_site_id",
            ),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(fields=["search", "site"], name="job_search_site_idx"),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(fields=["company"], name="job_company_idx"),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(fields=["location"], name="job_location_idx"),
        ),
    ]

